global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 192.168.192.100:9090
- job_name: node_dev100
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 192.168.192.100:9100
- job_name: cadvisor
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 192.168.192.100:8080