services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.qq.com:465
      - GF_SMTP_USER=your_qq_email@qq.com
      - GF_SMTP_PASSWORD=your_account_auth_code
      - GF_SMTP_FROM_ADDRESS=your_qq_email@qq.com
      - GF_SMTP_FROM_NAME=Grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
volumes:
  prom_data: